---
kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
      event: push
      status: success
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/ababot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

  - name: Deploy prod
    image: abakus/ansible-deploy
    when:
      branch:
        - master
      event: [push]
      status: [success]
    settings:
      playbook: /infrastructure/office/playbooks/deploy.yml
      repository:
        from_secret: infra_repository
      tags:
        - ababot
      limit: srv07
      inventory: /infrastructure/inventory
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: infra_deploy_key
    depends_on:
      - docker