pipeline:
  tests:
    image: node:8
    when:
      event: push
    commands:
      - npm install
      - npm run lint
  docker:
    image: plugins/docker
    when:
      branch:
        - master
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/ababot
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
