---
kind: pipeline
type: docker
name: default

steps:
  - name: tests
    image: node:10
    when:
      event: [push]
    commands:
      - npm install
      - npm run lint

  - name: docker
    image: plugins/docker
    when:
      event: [push]
      branch:
        - master
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/ababot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
